# Generated by Django 6.0.1 on 2026-01-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='resolved_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
